"""Data models used throughout the briefing pipeline."""

from typing import List, Optional

from pydantic import BaseModel, Field


class Article(BaseModel):
    title: str
    link: str
    description: str = ""
    content: Optional[str] = None
    published: str = "Unknown"
    source: str
    category: str = "technology"


class GeneratedSummary(BaseModel):
    """Fields generated by the language model."""

    headline_ar: str = Field(description="عنوان الخبر باللغة العربية")
    summary_ar: str = Field(description="ملخص موجز للخبر باللغة العربية")
    summary_en: str = Field(description="A concise English summary of the article")
    key_points: List[str] = Field(description="أهم النقاط المستخلصة من الخبر")
    why_it_matters: str = Field(description="لماذا يهم هذا الخبر مجتمع التقنية")
    companies: List[str]
    technologies: List[str]
    confidence: float = Field(ge=0.0, le=1.0)


class BriefingItem(GeneratedSummary):
    source_url: str
    source_name: str = ""
    published: str = "Unknown"


class DailyBriefing(BaseModel):
    date: str
    items: List[BriefingItem]
    meta: dict
